version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
  backend:
    build:
      context: .
    expose:
      - 8888
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py create_users
      && python manage.py create_data
      && gunicorn config.wsgi -b 0.0.0.0:8888"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx